name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Build project
        run: |
          npm run build
          
      - name: Lint project
        run: |
          npm run lint
          
      - name: Test project
        run: |
          npm run test:unit
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
